import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import {
  ClerkProvider,
  ConvexClientProvider,
  ThemeProvider,
} from "@/providers";

import "@/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* eslint-disable-next-line better-tailwindcss/no-unregistered-classes */}
      <body className="using-mouse">
        <ThemeProvider>
          <ClerkProvider>
            <ConvexClientProvider>
              {children}
              <Toaster position="top-center" />
            </ConvexClientProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
