const extensionMap: Record<string, string> = {
  javascript: "js",
  jsx: "jsx",
  typescript: "ts",
  tsx: "tsx",
  python: "py",
  java: "java",
  php: "php",
  ruby: "rb",
  go: "go",
  rust: "rs",
  html: "html",
  css: "css",
  json: "json",
  xml: "xml",
  sql: "sql",
  shell: "sh",
  bash: "sh",
  csharp: "cs",
  cpp: "cpp",
  c: "c",
  swift: "swift",
  kotlin: "kt",
  scala: "scala",
  scss: "scss",
  sass: "sass",
  less: "less",
  yaml: "yaml",
  yml: "yml",
  markdown: "md",
  powershell: "ps1",
  dockerfile: "dockerfile",
  r: "r",
  matlab: "m",
  perl: "pl",
  lua: "lua",
  dart: "dart",
  vue: "vue",
  svelte: "svelte",
  solidity: "sol",
  haskell: "hs",
  clojure: "clj",
  erlang: "erl",
  elixir: "ex",
  fsharp: "fs",
  ocaml: "ml",
  nim: "nim",
  zig: "zig",
};

export function getFileExtension(lang: string): string {
  return extensionMap[lang.toLowerCase()] || "txt";
}
